### ISSUE TITLE
Any plan to migrate to Grails 3.x ?

### ISSUE THREAD

**Issue by rmondejar** [bgawel/yeoman-frontend#3]
Great plugin, really simple and effective! 

I'm wondering if you have any plan to implement a new version for Grails 3.x. 

Since there are a few code to adapt, it could be easy and very useful to combine with the proper Grails 3 profile (ex. micro-web or a possible rest-api).

Thanks in advance

**Comment by bgawel** [comment]
I have no plans to migrate to Grails 3.x. However if you would like to contribute to this task, you are more than welcome.
