### ISSUE TITLE
Integration with Generator Gulp Angular

### ISSUE THREAD

**Issue by ObiKerui** [bgawel/yeoman-frontend#6]
Great plugin, thanks for providing this! 

I'm using Yeoman but I'm using the 'generator-gulp-angular' generator (by user Swiip), so instead of grunt my project uses gulp for build tasks. As your plugin works with grunt would it be a lot of work to make your plugin work with my gulp project instead? For instance, if only a few files require changing can you tell me which these are?

Thanks!

**Comment by bgawel** [comment]
Have you tried to configure the plugin with Gulp without changing any files?
Please have a look at the following options: "yo.runappcmd.exe" and "yo.warcmd.exe" (http://bgawel.github.io/yeoman-frontend/guide/introduction.html). These two options are configured to run Grunt tasks by default. However you can configure them to run Gulp tasks instead of Grunt ones.
Please let me know if it works for you.

**Comment by ObiKerui** [comment]
Thanks. I created a new project and set the 'yo.runappcmd.exe' to 'gulp serve'. I can see that the yeoman frontend is loading and working as expected and if I navigate to localhost:3000 I can see the frontend application looks as expected and is responding to live updates. 

However, if I navigate to localhost:8080/GrailsBackend (my grails project url) I'm getting a 500 internal server error with the cause being:

'Error processing GroovyPageView: Error executing tag yo:index: Cannot get property 'text' on null object'

This error seems to stem from a filter written for the yo:index tag in grails-app\taglib\yeoman\frontend\YoTagLib.groovy: 

def yoResourceLocatorService
8:
9:    def index = { attrs ->
10:        out << yoResourceLocatorService.index.text
11:    }

The 'yoResourceLocatorService.index.text' is null. Any idea what the problem could be? I haven't added any extra code to the Grails Project yet, I've only installed the plugin. 

Thanks!

**Comment by bgawel** [comment]
It is probably like that because you have a different application structure than assumed by default. Check out the following options: yo.frontend.app.dir, yo.frontend.app.index, yo.frontend.tmp.dir

**Comment by ObiKerui** [comment]
The application structure is very different in the gulp project. I tried running the plugin with the original yeoman project (yeoman-generator-angular) as you have in your example for comparison. I get the following 404 errors, however, when I load the index.html page...

![problem](https://cloud.githubusercontent.com/assets/6961234/11093082/f2156bf2-887f-11e5-989f-fb6828bc47db.png)

As you can hopefully see, grails can't locate any of the files in my project's bower_components directory which is in the 'frontend' folder. although it can find the /scripts/app.js and /scripts/controllers/main.js which are links relative to the 'app' folder. 

How is your grails application able to find the bower_components folder?

**Comment by bgawel** [comment]
The plugin never aimed to work with Gulp.
